spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_project_f
    username: root
    password: 12344

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8080

security:
  jwt:
    secret-key: hollyshitthisshitishellastink:)))


